@startuml
|Client|
start
:get or create RSA keys;
|Server|
:save RSA keys;
|Client|
:get or create AES key;
:enrypt data;
:encode data with Base64;
|Server|
:save encrypted data;
|Client|
:encrypt AES key with RSA;
:encode key with Base64;
|Server|
:save encrypted AES key;
stop
@enduml
